---
version: 2.1

executors:
  golang:
    docker:
    - image: circleci/golang:1.14

jobs:
  build:
    executor: golang

    steps:
    - checkout
    - run: go mod download
    - run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
    - run: make -C software/earl style
    - run: make -C software/earl test
    - run: ./bin/goreleaser release --skip-publish --snapshot
    - persist_to_workspace:
        root: .
        paths:
        - dist
    - store_artifacts:
        path: dist

  release:
    executor: golang

    steps:
    - run: go mod download
    - run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
    - attach_workspace:
        at: .
    - run: ./bin/goreleaser release

workflows:
  version: 2
  earl:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
